### ISSUE TITLE
formulario creacion fundacion

### ISSUE THREAD

**Issue by chechocast** [betocastillo86/huellitasv2#12]
1. las ciudades cargan muy lento el autocompletar
2. un usuario normal no colocaria el http si digita la direccion de su red validar
![captura de pantalla 2017-06-05 a la s 9 38 11 a m](https://cloud.githubusercontent.com/assets/11667902/26788500/fe78f9c0-49d2-11e7-8e85-3e97c1a07d6e.png)

**Comment by betocastillo86** [comment]
Este lo estuve pensando y no lo voy a cambiar por ahora. Es que cualquiera de los dos puede ser igual de confuso. Entonces problemoslo a ver como nos va.
