### ISSUE TITLE
que no salga el boton ver mas si no hay elementos que mostrar de mas en todo lado aplica

### ISSUE THREAD

**Issue by chechocast** [betocastillo86/huellitasv2#15]

**Comment by betocastillo86** [comment]
Pero en donde lo vio especificamente. Porque así está en la mayoría de los casos.

**Comment by chechocast** [comment]
En todo lado en la lista de fundaciones en perdidos etc donde no haya mas de lo que se esta mostrando en la pantalla inicial

**Comment by betocastillo86** [comment]
el único lugar que vi fue en los perros de una fundación. Ya quedó corregido
