### ISSUE TITLE
en mascotas relacionadas no dejar el mismo perro, si no hay relacionadas que no salga esa casilla

### ISSUE THREAD

**Issue by chechocast** [betocastillo86/huellitasv2#16]
aqui cree a peludito y sale peludito

![captura de pantalla 2017-06-05 a la s 5 07 25 p m](https://cloud.githubusercontent.com/assets/11667902/26805439/89350520-4a11-11e7-8bc5-2a4845df350f.png)

**Comment by betocastillo86** [comment]
Corregido
