### ISSUE TITLE
Botón de ver todos 

### ISSUE THREAD

**Issue by betocastillo86** [betocastillo86/huellitasv2#19]
Cambiar Button por A en:
- Listados en el home de Ver todos, animales y fundaciones
- Detalle de fundacion: Ver todos los perros

**Comment by betocastillo86** [comment]
![image](https://user-images.githubusercontent.com/8453022/26942107-76a5e582-4c46-11e7-9573-802182566baa.png)
![image](https://user-images.githubusercontent.com/8453022/26942122-866d8fd8-4c46-11e7-9fbd-8ed117649a12.png)

**Comment by chechocast** [comment]
corregido
