### ISSUE TITLE
[PERDIDOS] Ajuste de Textos

### ISSUE THREAD

**Issue by ericaprado** [betocastillo86/huellitasv2#20]
1. ¿BUSCAS O ENCONTRASTE UNA MASCOTA PERDIDA?
Quitar la tilde de ENCONTRASTÉ

2. "Sugiero" cambiar el texto principal a: 
Este espacio busca crear una red de ayuda para encontrar perros y gatos perdidos a través de la publicación del caso o con el reporte de mascotas encontradas para agilizar ese final feliz tan esperado en este tipo de situaciones. Solo debes registrar los datos solicitados según el caso para que Huellitas sin Hogar publique y difunda la infomacion. 

3. Botón Publícala Aquí
Falta la tilde en Publícala

4. MASCOTAS REPORTADAS
"Sugiero" cambiar "MASCOTAS REPORTADAS" por "MASCOTAS PERDIDAS"

5. Solo busca por las caracteristicas del que quieras fuera tu huellita
Cambiar el texto a "Selecciona las características de tu perro o gato perdido"

**Comment by betocastillo86** [comment]
Corregido
