### ISSUE TITLE
[PUBLICAR PERDIDO] Ajustar mensaje de confirmación

### ISSUE THREAD

**Issue by ericaprado** [betocastillo86/huellitasv2#22]
Cuando se publica un perdido "sugiero" cambiar el texto de la confirmación por:

PUBLICACIÓN EXITOSA

Tu mascota ha sido publicada. A tu cuenta de correo llegará cualquier comentario recibido así que debes estar pendiente. Si tienes alguna inquietud escríbenos a Facebook haciendo clic aquí.

Aceptar

![image](https://user-images.githubusercontent.com/10680212/26955987-510696a2-4c80-11e7-88e9-f788a2d70bae.png)

**Comment by betocastillo86** [comment]
Corregido
