### ISSUE TITLE
[PERDIDO] Ajuste de textos

### ISSUE THREAD

**Issue by ericaprado** [betocastillo86/huellitasv2#23]
1. Agregar algo que me indique que estoy en la secciòn de perdidos. Ejemplo "Se busca"

2. Poner tilde a Género

3. En COMENTARIOS sugiero un texto como:
Has visto en algún lugar a esta huellita? Cualquier información es valiosa para nosotros!

4. En el label del campo poner tilde a Déjanos tu comentario

![image](https://user-images.githubusercontent.com/10680212/26956973-45fdb31a-4c87-11e7-97b5-9246b92631f3.png)

**Comment by betocastillo86** [comment]
Me ayuda con el punto 1? Es como para que la gente sepa donde está parada y que es un perro perdido.

**Comment by chechocast** [comment]
Quedaria en el texto Mascota perdida: Nombre

**Comment by betocastillo86** [comment]
Corregido
