### ISSUE TITLE
Estilos de botones en Mis huellitas

### ISSUE THREAD

**Issue by betocastillo86** [betocastillo86/huellitasv2#27]
@chechocast ud creó un estilo `.table .btn` que vuelve el botón azul, eso no me deja usar los botones de bootstrap porque se ven del mismo color. Por ejemplo:
![image](https://user-images.githubusercontent.com/8453022/27152174-9fb3d03a-5112-11e7-9374-f89760d9f2dc.png)

**Comment by chechocast** [comment]
corregido
