### ISSUE TITLE
la descripcion que sale en la tarjeta de la fundacion solo muestre los 210 primeros carateres el resto se omita y s muestre en la interna

### ISSUE THREAD

**Issue by chechocast** [betocastillo86/huellitasv2#28]
![captura de pantalla 2017-06-15 a la s 11 34 00 a m](https://user-images.githubusercontent.com/11667902/27191818-9cddfeec-51be-11e7-8bda-87ee7d3ae47f.png)

**Comment by betocastillo86** [comment]
ajustado
