### ISSUE TITLE
corregir esto no es un filtro o peude ser filtro pero dejar como el original

### ISSUE THREAD

**Issue by chechocast** [betocastillo86/huellitasv2#29]
![captura de pantalla 2017-06-15 a la s 11 56 44 a m](https://user-images.githubusercontent.com/11667902/27192634-be3598ae-51c1-11e7-884f-ad7665773cda.png)
![captura de pantalla 2017-06-15 a la s 11 56 52 a m](https://user-images.githubusercontent.com/11667902/27192635-be37c642-51c1-11e7-8189-e7a8b13671b9.png)

**Comment by betocastillo86** [comment]
Corregido
