### ISSUE TITLE
Ajustes de diseño pendientes

### ISSUE THREAD

**Issue by betocastillo86** [betocastillo86/huellitasv2#3]
1 Cambiar el botón de los listados "conocer mas" o "ver más" a A en vez de BUTTON
2 Div con diseño para cuando no se encuentran resultados en las diferentes busquedas
3 Botón "ver más" de comentarios
4 Div de NO HAY COMENTARIOS en las internas (Mismo punto 2)
5 arreglar boton de ver todos los perros de un refugio. Al pasarlo de button a A se dañó
6 Redes sociales en el detalle del refugio
7 mostrar NO HAY RESULTADOS en mypets (Mismo punto 2)
8 mostrar NO HAY RESULTADOS en forms (Mismo punto 2)
9 Pantalla 404
10 Hacer imagenes para facebook app

**Comment by chechocast** [comment]
no entiendo este 2 Div con diseño para cuando no se encuentran resultados en las diferentes busquedas

**Comment by chechocast** [comment]
la pagina 404 quedo en cortes/templates/404.html
