### ISSUE TITLE
el menu de usuario y el menu general se pisan

### ISSUE THREAD

**Issue by chechocast** [betocastillo86/huellitasv2#4]
Que al abrir el uno se cierre el otro si se encuentra abierto, si se puede agregar algun tipo de animacion al desplegar el menu seria bueno

![captura de pantalla 2017-06-05 a la s 9 10 40 a m](https://cloud.githubusercontent.com/assets/11667902/26787237/e8233fea-49ce-11e7-95cf-e689fdd6d9de.png)

**Comment by betocastillo86** [comment]
corregido
