### ISSUE TITLE
habiamos quedado que solo respondia el creador del animal o de la fundacion los comentarios

### ISSUE THREAD

**Issue by chechocast** [betocastillo86/huellitasv2#40]
el que esta comentando tambien se esta respondiendo

![captura de pantalla 2017-06-21 a la s 10 42 46 a m](https://user-images.githubusercontent.com/11667902/27393367-b8aa2a56-566e-11e7-82a0-040ec0e0ebe8.png)

**Comment by betocastillo86** [comment]
Ah si, pero lo dejé abierto. No sobra de todas maneras.
