### ISSUE TITLE
Cuando entro a una fundacion que no es mia sale el control de mis huellitas, quitar solo debe salir en la que es mi fundacion si no no

### ISSUE THREAD

**Issue by chechocast** [betocastillo86/huellitasv2#41]
![captura de pantalla 2017-06-21 a la s 11 35 09 a m](https://user-images.githubusercontent.com/11667902/27395580-dc206dd6-5675-11e7-9735-667e04cd2d2c.png)

**Comment by betocastillo86** [comment]
Corregido
