### ISSUE TITLE
verificar el como se sube esta imagen de fundacion

### ISSUE THREAD

**Issue by chechocast** [betocastillo86/huellitasv2#8]
![captura de pantalla 2017-06-05 a la s 9 20 20 a m](https://cloud.githubusercontent.com/assets/11667902/26787614/46c9123a-49d0-11e7-9c23-6e9fafa1dffb.png)

**Comment by betocastillo86** [comment]
Acuerdese que esto lo habiamos hablado. Y quedamos que las imagenes se iban a cortar de la misma manera para animales que para fundaciones
